server.port=8081
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.application.name=React Example with SpringBoot
# For Development Uncomment
spring.web.resources.static-locations=file:src/main/resources/static/
